
[prune]
  go-tests = true
  unused-packages = true

# Jaeger stuffs

[[constraint]]
  name = "github.com/jaegertracing/jaeger"
  version = "^1.18.0"

[[constraint]]
  name = "github.com/apache/thrift"
  version = "^0.10.0"

# Other stuffs

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "^1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/onrik/logrus"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.3"


[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"
