
[prune]
  go-tests = true
  unused-packages = true

# Jaeger stuffs

[[constraint]]
  name = "github.com/jaegertracing/jaeger"
  version = "1.7.0"

[[override]]
  name = "github.com/uber/tchannel-go"
  version = "v1.1.0"

[[override]]
  name = "github.com/uber/jaeger-lib"
  version = "^1.5.0"

[[override]]
  name = "github.com/apache/thrift"
  version = "0.9.3"

[[override]]
  name = "github.com/uber/jaeger-client-go"
  version = "^2.11.0"

# Other stuffs

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "^0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/onrik/logrus"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
