---

version: "3"
services:
  traefik:
    image: traefik:alpine
    links:
      - web
      - jaeger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80
      - 8080
    command: >
      traefik -l debug
      --tracing.jaeger.localagenthostport=jaeger:6831
      --docker

  web:
    image: nginx:alpine
    labels:
      traefik.frontend.rule: Host:traefik

  client:
    image: byrnedo/alpine-curl
    links:
      - traefik
    command: --silent http://traefik/

  jaeger:
    image: jaeger-lite
    environment:
      ADMIN_LISTEN: 0.0.0.0:8080
    ports:
      - 8080