---
version: "3"
services:
  traefik:
    image: traefik:alpine
    links:
      - web-front
      - jaeger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik.toml
    ports:
      - 80
      - 8080
    command: >
      traefik -c /etc/traefik.toml

  web-front:
    image: nginx:alpine
    labels:
      traefik.frontend.rule: Host:traefik

  jaeger:
    image: jaeger-lite
    ports:
      - 8080
    volumes:
      - ./jaeger-lite.yml:/etc/jaeger-lite.yml:ro

  client:
    image: byrnedo/alpine-curl
    links:
      - traefik
    command: --silent http://traefik/

  promclient:
    image: byrnedo/alpine-curl
    links:
      - jaeger
    command: --silent http://jaeger:8080/metrics
